"""update

Revision ID: c72d1486a4f5
Revises: f0bc781c2c55
Create Date: 2018-04-27 14:06:07.899931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c72d1486a4f5'
down_revision = 'f0bc781c2c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobseeker', sa.Column('resume', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobseeker', 'resume')
    # ### end Alembic commands ###
